services:
  bitbites-api:
    image: ${REPO}/bitbites-api
    build:
      context: .
    env_file:
      - .env
    networks:
      - bites-api
    ports:
      - 8080:8080

networks:
  bites-api:
    external: true
